# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: PetKit BLE Bridge"
  org.opencontainers.image.description: "Provides a BLE Bridge for PetKit Devices via MQTT."
  org.opencontainers.image.source: "https://github.com/pdiegmann/ha-petkit-ble-bridge"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2024.11.2"
#cosign:
#  # The identity is *our* identity that we use to sign this image.
#  # It is used to verify the safety of reusing the cache
#  identity: https://github.com/wez/govee2mqtt/.*
#  # The base_identity is the identity of the base images specified
#  # by the build_from section above
#  base_identity: https://github.com/home-assistant/docker-base/.*