name: "PetKit BLE Bridge"
description: "Provides a BLE Bridge for PetKit devices."
version: "1.0.0"
slug: "petkit-ble-bridge"
url: "https://github.com/pdiegmann/ha-petkit-ble-bridge/tree/main/petkit-ble-bridge"
#image: "ghcr.io/pdiegmann/{arch}-petkit-ble-bridge"
init: false
host_dbus: true
usb: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  address: ""
  mqtt: false
  mqtt_broker: ""
  mqtt_port: 0
  mqtt_user: ""
  mqtt_password: ""
  logging_level: INFO
schema:
  address: str(4,10)
  mqtt: bool
  mqtt_broker: "str?"
  mqtt_port: "port?"
  mqtt_user: "str?"
  mqtt_password: "password?"
  logging_level:
    - DEBUG
    - INFO
    - WARNING
    - ERROR
